### ISSUE TITLE
Support Istio

### ISSUE THREAD

**Issue by rsnj** [microsoft/ApplicationInsights-Kubernetes#169]
Using this library with Istio does not work. Istio seems to be blocking the internal calls to the AKS Kubernetes Management Server because they are seen to be external to the cluster. I have opened a ticket with Istio a while back and have no luck finding a solution. Is there a common URL or IP Address I can to my Istio configuration?

More information can be found here:
https://github.com/istio/istio/issues/8696

**Comment by xiaomi7732** [comment]
@lisaguthrie by chance, do you know whom to contact for AKS configurations? Thanks in advance.

**Comment by adinunzio84** [comment]
We had a similar problem with kubernetes/client-go#527. We worked with Microsoft to get some information, and this information may be relevant to your case too:
* If you use "includeIPRanges" so the Envoy proxies ignore egress traffic, the problem no longer happens, but then you lose some Istio functionality for egress traffic. If you don't use that, then the rest of the following apply:
* Since the master node is accessed with a FQDN, you need a ServiceEntry and VirtualService to access it (as mentioned in the client-go issue). Once you set this up though, you'll probably still have issues with connections abruptly closing, so more info on that:
* The load balancer sitting in between your AKS cluster and the master node watches for idle connections and closes any connections that are idle for 5 minutes
* The load balancer does not send a TCP RESET packet to applications signalling the closed connection. There are plans to support a standard load balancer with AKS [which will eventually support TCP RESETs](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-reset), in which case the applications will know to reconnect to the master node.
* Applications can keep the connection alive by sending TCP KeepAlive packets, but the Envoy proxy currently does not support that: envoyproxy/envoy#3634
* You can tell Istio to only use one request per connection in the envoy proxies using a DestinationRule, and when combined with disabling HTTP KeepAlive, that should work. This might not be particularly performance-friendly.

**Comment by xiaomi7732** [comment]
Close this issue since this is tracked by https://github.com/istio/istio/issues/8696
