### ISSUE TITLE
Application map not showing services running in Azure Kubernetes

### ISSUE THREAD

**Issue by karthi-sn** [microsoft/ApplicationInsights-Kubernetes#232]
I have referred this article (https://docs.microsoft.com/en-us/azure/architecture/microservices/logging-monitoring, https://github.com/microsoft/ApplicationInsights-Kubernetes) 

issue - Application map not showing any data about services running inside Azure Kubernetes
setup - have multiple services running in Azure Kubernetes, calling all those from API management, but only API management is showing in Application map, none of services running inside Azure Kubernetes are showing

SDK - Dotnet 5.0

**Comment by karthi-sn** [comment]
application insight image
![image](https://user-images.githubusercontent.com/41871740/121880456-a7f3e980-cd2b-11eb-9531-2e41f8c17ddf.png)

services running inside Azure Kubernetes
![image](https://user-images.githubusercontent.com/41871740/121880767-0620cc80-cd2c-11eb-85d0-a6c900d13d45.png)

**Comment by xiaomi7732** [comment]
@karthi-sn thanks for the report. It doesn't seem like owned by this project.
@OsvaldoRosado Do you know where shall I redirect this issue to?

**Comment by karthi-sn** [comment]
@xiaomi7732 what you mean by **_It doesn't seem like owned by this project_**
this issue is not related to this GitHub project?

**Comment by xiaomi7732** [comment]
Yes @karthi-sn Thanks for the ask. Here's my understand of the issue:

You want to see multiple dots showing up on application insights map for your services, one dot for one service, like what shows up in this [distributed tracing](https://docs.microsoft.com/en-us/azure/architecture/microservices/logging-monitoring#example-of-distributed-tracing), right? And what you are seeing is that there's only 1 node shows up for your app in the application insights map, correct?

Based on that, we will need to understand what are the property on the telemetry objects that is used to distinguish services - and I assume that is **cloud_roleName** for single iKey - that's where I need help from @OsvaldoRosado to confirm.

_Now, why I said this project didn't own that: because what this project provide are all customDimentions that application insights map shall not have knowledge on. That means, chasing this down will leads to a dead end._

That said, my suggestions for troubleshooting:

* Query all your recent requests in your application insights instance, see how many roleName are there:

For example, in one of our cluster:

```KQL
requests
| summarize sum(itemCount) by cloud_RoleName
```

I got this:
![image](https://user-images.githubusercontent.com/3674549/121963265-b8ea2e00-cd1e-11eb-8aa4-5b824d5bddcd.png)

Notice there are 3 groups of could_RoleName and my application map looks like this:

![image](https://user-images.githubusercontent.com/3674549/121963537-18e0d480-cd1f-11eb-9400-c18212cdf6c7.png)

I assume, in your case, based on the screenshot you shared, you are seeing 2 roleNames.

Okay, if you expect more roleName to show up, the next step is to understand where are those roleName suppose to be set and why are they missing.

There are some quick checks:

1. Is every service sending telemetry objects (request telemetries specifically,) to application insights - if the service is not reporting to application insights, they won't show up on the map;
    1. Tips: Query the telemetry objects, group them by cloud_roleInstance to see where did your telemetries come from;
1. If the telemetry records are there, what's the value for roleName? Are those roleName mapped back to your service or are they map to something else?

I have enough assumptions so far. Could you post us which case matches your issue? Or point out if I have a misunderstanding. Thanks!

**Comment by karthi-sn** [comment]
@xiaomi7732  
your right on what's my issue and what was I expecting, I'll check those and see is missing.

Thanks a lot for your detailed reply.

**Comment by xiaomi7732** [comment]
No problem. I'll close this issue for now. Feel free to file new issue if more help is needed.

**Comment by xiaomi7732** [comment]
@karthi-sn I heard back from @OsvaldoRosado offline. Here's a read about how application map works:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-map?tabs=net#set-or-override-cloud-role-name

Quote a quick part that related:

> Application Map uses the cloud role name property to identify the components on the map.

Notice, the post is talking about manual cloudName overwriting, you may or may not need it according to what is already there on cloudName and does it fit your need.

Let me know if you need more clarification. :-)

**Comment by karthi-sn** [comment]
@xiaomi7732  
Thanks for link, it answers my question, and I may know, what to do next.
Thanks again @xiaomi7732  @OsvaldoRosado , you guys are awesome.
and I'm closing this issue
