### ISSUE TITLE
Refresh all examples to .NET 6

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-Kubernetes#265]
The current position of [examples](./examples) are a bit awkward:

* They have been out of date (.NET Core 2.0 projects).
* The are unnecessary complex (A lot of ASP.NET Core MVC projects).

I think we shall learn the lesson:

I am proposing we providing new examples based on most simple project types that make sense:

- [x] WebAPI for ASP.NET Core (The bootstrap for WebAPI is the common base for various projects.)
  - [x] Minimal API
  - [x] Traditional Controller based
- [x] .NET Worker Service for console application
  * Worker service isn't the simplest console application, but fits best in K8s scenario.
- [x] Hosting startup example

What do you think?

**Comment by karolz-ms** [comment]
Overall I think it is a great idea! 👍 

With regards to minimal API vs controller-style: ideally we should have at least one example of each kind. The reason is , doing greenfield development, minimal API might be more popular, but there is a lot of existing apps that use controller-style and might need to be moved to K8s. (channeling ASP.NET PM here)

**Comment by xiaomi7732** [comment]
Hi @karolz-ms I think that is a good idea!

**Comment by xiaomi7732** [comment]
All examples planned have been updated. Close this issue. Please open new issues if you want examples for other scenarios.
