### ISSUE TITLE
Unable to enable self diagnostics for ApplicationInsights.Kubernetes in ASP.NET Core 2.0

### ISSUE THREAD

**Issue by mumarniaz** [Microsoft/ApplicationInsights-Kubernetes#70]
I am trying to configure ApplicationInsights Kubernetes plugin in my ASP.NET Core 2.0 application. I have followed the instructions and deployed the container image to kubernetes cluster (Azure Kubernetes Service with kubernetes 1.8.1 as well as on minikube with kubernetes 1.8.0). But I am unable to get any kubernetes related stats in the app-insights portal. I am trying to enable self diagnostics for ApplicationInsights.Kubernetes using the instructions [here](https://github.com/Microsoft/ApplicationInsights-Kubernetes/wiki/%5BAdvanced%5D-How-to-enable-self-diagnostics-for-ApplicationInsights.Kubernetes) but its giving me error on line:

`.ConfigureLogging(f => f.AddConsole(LogLevel.Trace))`

The error is:
`Error	CS1503	Argument 2: cannot convert from 'Microsoft.Extensions.Logging.LogLevel' to 'System.Action<Microsoft.Extensions.Logging.Console.ConsoleLoggerOptions>'`

It seems like the .net core 2.0 packages does not have these functions to add console. I have added below lines but still no kubernetes logs and no stats on app insight portal.

`.ConfigureLogging(logging => logging.SetMinimumLevel(LogLevel.Trace))`

What could be the issue?

**Comment by d3r3kk** [comment]
Perhaps (as this document is a draft from back in May) [this API has changed](https://github.com/aspnet/Announcements/issues/241). [I found this article ](https://ardalis.com/configuring-aspnet-core-apps-with-webhostbuilder) that suggests that your ConfigureLogging line would be changed to:

    .ConfigureLogging(f => f.AddConsole(), Microsoft.Extensions.Logging.LogLevel.Trace)

... and you can choose from [log level values here.](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel?view=aspnetcore-2.0)

**Comment by mumarniaz** [comment]
Thanks @d3r3kk 
But this won't work because `ConfigureLogging` fucntion is expecting only one parameter of type `Action`

**Comment by brahmnes** [comment]
In ASP.NET core 2.0, it looks like ConfigureLogging has changed from taking Action<ILoggingFactory> to Action<ILoggingBuilder>. 

Here is the new AddConsole method
[https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.consoleloggerextensions.addconsole?view=aspnetcore-2.0#Microsoft_Extensions_Logging_ConsoleLoggerExtensions_AddConsole_Microsoft_Extensions_Logging_ILoggingBuilder_](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.consoleloggerextensions.addconsole?view=aspnetcore-2.0#Microsoft_Extensions_Logging_ConsoleLoggerExtensions_AddConsole_Microsoft_Extensions_Logging_ILoggingBuilder_)

You should be able to do this:
`.ConfigureLogging(f => f.AddConsole(Microsoft.Extensions.Logging.LogLevel.Trace))`

**Comment by PeterRockstars** [comment]
@brahmnes  That doesn't work, as AddConsole(ILoggerFactory, LogLevel) takes an ILoggerFactory, not an ILoggingBuilder..
I'm struggling with the same thing. How do I get to the ILoggerFactory?

**Comment by PeterRockstars** [comment]
This seems to work, sort-of:
.ConfigureLogging(builder => builder
        .SetMinimumLevel(LogLevel.Trace)
        .AddConsole())

It gives me trace output when I do this:
      public HomeController(ILoggerFactory loggerFactory)
      {
        _logger = loggerFactory.CreateLogger<HomeController>();
        _logger.LogTrace("TRACE");
      }

But it doesn't show any of the App Insights logging shown in the example. Curiously, I do see that output in the debug window in Visual Studio.

**Comment by brahmnes** [comment]
Did you add the call to UseApplicationInsights()?

**Comment by PeterRockstars** [comment]
@brahmnes Yes, I did. 

It seems that in this line:

`ILoggerFactory loggerFactory = (ILoggerFactory)services.FirstOrDefault(s => s.ServiceType == typeof(ILoggerFactory))?.ImplementationInstance;`

The ImplementationInstance field is null

**Comment by brahmnes** [comment]
Hi Peter,

Application Insights needs to be configured with the LoggerFactory, otherwise ILogger isn't aware of Application Insights. Here is a related post: [https://stackoverflow.com/questions/45022693/using-application-insights-with-iloggerfactory](https://stackoverflow.com/questions/45022693/using-application-insights-with-iloggerfactory)

The extension method AddApplicationInsights is in Microsoft.ApplicationInsights.AspNetCore

**Comment by xiaomi7732** [comment]
There are break changes in the configuration settings for ASP.NET Core 2.0. We shall update the library to support it better. I'll look into this issue post 1.0.0-beta2

**Comment by xiaomi7732** [comment]
Okay, give it a deep look. There are 2 issues.
1. The instructions to enable self-diagnostics for ApplicationInsights.Kubernetes needs to be updated because of the way config logger provider changes. @PeterRockstars basically nailed the solution. **I'll update the document to reflect the changes.** One side note is that in HomeController, dependency injection upon `ILogger<>` than `ILoggerFactory` is more recommended:
```csharp
    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
        _logger.LogTrace("TRACE");
    }
```
That should address @mumarniaz 's issue.

2. @PeterRockstars is looking for more logs - logs from the real application insights library. If I understand it correct, you are looking for additional entries like it below:
```
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.5789ad108b394f8a88dc632d1342d5e0.Message","time":"2018-01-03T23:48:52.4627170Z","iKey":"i-do-not-tell-you-my-ikey","tags":{"ai.application.ver":"1.0.0.0","ai.user.id":"ldoLQ","ai.operation.parentId":"|c2390d17-42b31bbca592ecb8.","ai.operation.id":"c2390d17-42b31bbca592ecb8","ai.cloud.roleInstance":"my-machine-name","ai.internal.sdkVersion":"aspnet5c:2.1.1","ai.location.ip":"::1","ai.internal.nodeName":"xxx","ai.operation.name":"GET /lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2","ai.session.id":"1rbWZ"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"The file /lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 was not modified","severityLevel":"Information","properties":{"Path":"/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2","AspNetCoreEnvironment":"Development","CategoryName":"Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware","DeveloperMode":"true","{OriginalFormat}":"The file {Path} was not modified"}}}}
```
I think that is totally reasonable during the diagnostic session, you want to see all the way till temelemtry is actually sent, that is, however, not within control of AI.Kubernetes. To make the scenario work in ASP.NET Core 2.0, this work item needs to be addressed first in AI.Aspnetcore:
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/536 as an active work item.

**Comment by PeterRockstars** [comment]
@xiaomi7732 Thanks for the deep look, glad we got it figured out. And you're absolutely right on point 2, that is what I was looking for.

**Comment by xiaomi7732** [comment]
@PeterRockstars Thank you for the confirm!

**Comment by xiaomi7732** [comment]
Guys, thanks for raising the issue. The wiki has been updated to provide an example for ASP.NET Core 2.0 Web Apps to enable self-diagnostics.
https://github.com/Microsoft/ApplicationInsights-Kubernetes/wiki/%5BAdvanced%5D-How-to-enable-self-diagnostics-for-ApplicationInsights.Kubernetes

I am closing this issue since there is no more action could be taken in this repo. Please keep an eye on the issue of AI.AspNetCore mentioned above.
